"""empty message

Revision ID: 38fda5e9d60c
Revises: 49f15791f7ef
Create Date: 2022-06-27 00:36:39.069188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fda5e9d60c'
down_revision = '49f15791f7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'thumbnail')
    # ### end Alembic commands ###
